Repository jenkinsci/github-checks-plugin, pull requests merged in 2020-10, with the labels that each got.

#60 Cleanup pom
  pom.xml
Labels: chore

#64 Remove SKIPPED conclusion, use CANCELLED instead
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksDetails.java
Labels: bug

#70 Fix check reporting when using shared library
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherFactory.java
Labels: bug

#66 Add GitHub scm source implementation for status checks properties
  README.md
  docs/images/status-checks-properties.png
  pom.xml
  src/main/java/io/jenkins/plugins/checks/github/GitHubSCMSourceStatusChecksProperties.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubSCMSourceStatusChecksTrait.java
  src/main/resources/io/jenkins/plugins/checks/github/GitHubSCMSourceStatusChecksTrait/config.jelly
  src/test/java/io/jenkins/plugins/checks/github/GitHubSCMSourceStatusChecksPropertiesTest.java
Labels: enhancement
