Repository jenkinsci/github-checks-plugin, pull requests merged in 2020-08, with the labels that each got.

#13 Publish checks for job
  pom.xml
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksContext.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherFactory.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubContextResolver.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubSCMFacade.java
  src/test/java/io/jenkins/plugins/checks/github/GitHubCheckRunPublishITest.java
  src/test/java/io/jenkins/plugins/checks/github/GitHubChecksContextTest.java
  src/test/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherFactoryTest.java
Labels: enhancement

#17 Print console log
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherFactory.java
  src/test/java/io/jenkins/plugins/checks/github/GitHubCheckRunPublishITest.java
  src/test/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherFactoryTest.java
Labels: enhancement

#19 Simple null checks for listeners
  pom.xml
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherFactory.java
Labels: bug

#26 Add support for GitSCM sources
  pom.xml
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksContext.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisher.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherFactory.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubSCMFacade.java
  src/main/java/io/jenkins/plugins/checks/github/GitHubSCMSourceChecksContext.java
  src/main/java/io/jenkins/plugins/checks/github/GitSCMChecksContext.java
  src/main/java/io/jenkins/plugins/checks/github/SCMFacade.java
  src/test/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherFactoryTest.java
  src/test/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherITest.java
  src/test/java/io/jenkins/plugins/checks/github/GitHubSCMSourceChecksContextTest.java
  src/test/java/io/jenkins/plugins/checks/github/GitSCMChecksContextITest.java
Labels: enhancement

#38 Update readme
  README.md
  doc/activity.puml
  doc/classes-design.puml
  doc/component-design.puml
  docs/images/coverage-checks.png
  docs/images/failed-checks.png
  docs/images/github-checks-plugin-cover.png
  docs/images/github-status.png
  docs/images/warning-checks.png
Labels: documentation

#41 Add a new AssertJ template that does not produce deprecated warnings
  etc/assertj-templates/has_assertion_template.txt
Labels: chore
