Repository jenkinsci/github-checks-plugin, pull requests merged in 2021-01, with the labels that each got.

#102 Add options to skip GitHub Branch Source notifications
  src/main/java/io/jenkins/plugins/checks/github/status/GitHubSCMSourceStatusChecksTrait.java
  src/main/resources/io/jenkins/plugins/checks/github/status/GitHubSCMSourceStatusChecksTrait/config.jelly
Labels: enhancement

#107 Remove unstable windows builds on community servers.
  Jenkinsfile
Labels: chore

#105 fix: expose GitHubChecksContext outside the package
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksContext.java
Labels: chore

#106 Support arbitrary enterprise url in GitSCMContext.
  src/main/java/io/jenkins/plugins/checks/github/GitSCMChecksContext.java
Labels: bug

#101 Truncate long text fields
  src/main/java/io/jenkins/plugins/checks/github/GitHubChecksDetails.java
Labels: enhancement
