Repository jenkinsci/github-checks-plugin, pull requests merged in 2023-04, with the labels that each got.

#325 Remove Java 8 CI
  .github/workflows/maven.yml
Labels: chore

#307 Standardized & simplified & updated build & test infrastructure
  Jenkinsfile
  pom.xml
  src/main/resources/index.jelly
  src/test/java/io/jenkins/plugins/checks/ArchitectureTest.java
  src/test/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherITest.java
  src/test/java/io/jenkins/plugins/checks/github/GitSCMChecksContextITest.java
  src/test/java/io/jenkins/plugins/checks/github/config/GitHubChecksConfigITest.java
  src/test/java/io/jenkins/plugins/checks/github/status/GitHubSCMSourceStatusChecksTraitTest.java
Labels: developer

#330 Enable automated release
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: developer

#332 Re-enable integration tests
  pom.xml
  src/test/java/io/jenkins/plugins/checks/github/GitHubChecksPublisherITest.java
  src/test/java/io/jenkins/plugins/checks/github/GitSCMChecksContextITest.java
  src/test/java/io/jenkins/plugins/checks/github/config/GitHubChecksConfigITest.java
  src/test/java/io/jenkins/plugins/checks/github/status/GitHubSCMSourceStatusChecksTraitTest.java
  src/test/resources/__files/create-access-token.json
  src/test/resources/__files/get-app.json
  src/test/resources/__files/list-installations.json
  src/test/resources/__files/rate-limit.json
  src/test/resources/mappings/create-access-token.json
  src/test/resources/mappings/get-app.json
  src/test/resources/mappings/list-installations.json
  src/test/resources/mappings/rate-limit.json
Labels: tests
